/* Cartas de Evento (transcritas de las cartas originales).
   lvl: b azul · g verde · y amarilla · o naranja · r roja.  act: Acto (estrellas); 5 = carta de Fin.
   sp: Evento Especial.  r4 · inf ('B' = tirada de Brote) · al (Alimentación: 0,1,2 ó 'd' = tirada) · z (rutas) · acc (Acciones de Evento).
   El Presión Zed (Z) se ignora en solitario. Imágenes: assets/cartas/e_<id>.jpg */
'use strict';
const EV = {};
function ev(id, name, lvl, act, r4, inf, al, z, acc, txt, o) { EV[id] = Object.assign({ id, name, lvl, act, r4, inf, al, z, acc, txt, sp: 0 }, o || {}); }
const ALL = ['*'];

/* ---- AZULES ---- */
ev('cardio', 'Regla n.º 7: Cardio', 'b', 1, 1, 'B', 1, ['F','F'], 1, ['Al inicio: coloca 1 nueva unidad Zed en un espacio Inicial vacío (a tu elección); si no hay, en el Inicial con la unidad Zed de menor Fuerza.', 'Si un Zed entra en un espacio con Civiles o un Héroe este turno, puedes retirar esa unidad en lugar de luchar.']);
ev('cabana', 'Encuentras una cabaña de caza', 'b', 1, 0, 0, 'd', ['M','F'], 3, ['Al final de esta fase: si una unidad de jugador está en el Campamento, obtienes 2 de Munición. (¡Botín!)']);
ev('armados', 'Civiles Bien Armados', 'b', 1, 0, 0, 1, ['B','M'], 2, ['Al inicio: pon la ficha de «Bien Armados» en una unidad de Civiles Normales. Hasta que acabe en el Cementerio recibe 1 columna a favor en todos sus combates Cuerpo a Cuerpo y ataques con Arma de Fuego.']);
ev('asalto_m', 'Asalto nocturno en la Montaña', 'b', 2, 0, 'B', 'd', ['M'], 1, ['Al inicio: +1 de Infección por cada unidad Zed en la ruta de la Montaña. Coloca un nuevo Zed en su espacio Inicial.', 'Las unidades defensoras no reciben Modificador por Terreno durante esta fase.'], { assault: 'M' });
ev('asalto_f', 'Asalto nocturno en las Afueras', 'b', 2, 0, 'B', 1, ['F'], 2, ['Al inicio: +1 de Infección por cada unidad Zed en la ruta de las Afueras. Coloca un nuevo Zed en su espacio Inicial.', 'Sin Modificador por Terreno para los defensores durante esta fase.'], { assault: 'F' });
ev('asalto_b', 'Asalto nocturno en el Bosque', 'b', 2, 2, 'B', 'd', ['B'], 2, ['Al inicio: +1 de Infección por cada unidad Zed en la ruta del Bosque. Coloca un nuevo Zed en su espacio Inicial.', 'Sin Modificador por Terreno para los defensores durante esta fase.'], { assault: 'B' });
ev('asalto_a', 'Asalto nocturno en la Autovía', 'b', 2, 1, 'B', 1, ['A','A'], 1, ['Al inicio: +1 de Infección por cada unidad Zed en la ruta de la Autovía. Coloca un nuevo Zed en su espacio Inicial.', 'Sin Modificador por Terreno para los defensores durante esta fase.'], { assault: 'A' });
ev('bajo_pies', 'Justo bajo nuestros pies', 'b', 2, 0, 'B', 0, ['A','F','M'], 2, ['Al inicio, roba Destino: elige una unidad de Civiles o Héroe en la Ruta Destinada (no en el Centro ni en un espacio Inicial): sufre de inmediato un ataque Cuerpo a Cuerpo en la columna «Igual» (aplica Modificadores por Terreno). Si eran Civiles Resistiendo, dejan de serlo.', 'Tu unidad solo sufre Impactos, no se retira.']);
ev('propagacion', 'La «propagación» de la enfermedad Zed', 'b', 2, 1, 'B', 'd', ['A','B','B'], 3, ['Al inicio, roba Destino: coloca un nuevo Zed en el espacio Inicial de la Ruta Destinada. Durante este turno, por cada unidad de Civiles Normales eliminada o enviada al Hospital tras su tirada de Salvación, coloca un nuevo Zed en el espacio donde estaba.']);
ev('pelo', '¿Me tomas el pelo?', 'b', 2, 2, 0, 'd', ALL, 1, ['Al inicio: 1. Coloca un nuevo Zed en el espacio Inicial de cada ruta (límite de agrupamiento). 2. Retira todas las fichas de Impacto de los Zeds.', 'Después se activan todas las rutas (tú eliges el orden).'], { sp: 1, order: 1 });
ev('odio', 'Odio cuando pasa eso', 'b', 4, 0, 'B', 'd', ['A','F','F'], 3, ['Al inicio: sustituye todas las unidades Zed Normales de Fuerza 3 o menos por nuevas unidades al azar con Fuerza completa (empezando por las más cercanas al Centro). Si tenían fichas, se descartan.']);
ev('heroe_b', 'Llega un Héroe', 'b', 3, 1, 'B', 0, ['A','F','B'], 2, ['Al inicio: coge un nuevo Héroe disponible al azar y colócalo en el Centro de la Ciudad o en cualquier espacio Inicial.']);
ev('keepcalm', '«Keep calm» y mata Zeds', 'b', 4, 1, 'B', 0, ['M','A'], 2, ['Al inicio: elige un Héroe en juego; obtiene 2 columnas a favor al atacar Cuerpo a Cuerpo únicamente este turno (solo si es el atacante).']);
ev('mina', '¡Explosión en la Mina!', 'b', 3, 1, 0, 0, ['M','F','A'], 2, ['Al inicio: cualquier unidad en la Mina Lucky Strike sufre 1 Impacto y debe retirarse.', 'Ninguna unidad podrá entrar en ese espacio durante el resto del turno («No Pasar»).']);
ev('noche', 'Al caer la noche', 'b', 3, 1, 'B', 'd', ['A','B'], 4, ['Al inicio: +1 de Infección por cada unidad Zed en la ruta de la Autovía. Coloca un nuevo Zed en su espacio Inicial.', 'Sin Modificador por Terreno para los defensores durante esta fase.'], { assault: 'A' });
ev('resistentes', 'Zeds Resistentes', 'b', 3, 1, 'B', 1, ['M','M'], 3, ['Al inicio: 1. Coloca un nuevo Zed en el Inicial de la Montaña. 2. Pon la ficha de Resistentes en la unidad Zed Normal más fuerte (a tu elección si hay empate): cada Impacto que reciba se anula con 1-3 en un dado.']);
ev('que_olor', '¿Qué es ese olor?', 'b', 3, 0, 'B', 2, ['A','M','B'], 2, ['Al final de esta fase: elige una unidad de jugador que no esté en el Centro; coloca una unidad Zed Normal por su cara de Fuerza reducida en ese espacio y resuelve un combate Cuerpo a Cuerpo normal. Si la unidad Zed sobrevive y gana, dale la vuelta a su cara de Fuerza completa (conserva sus Impactos). Si pierde, se retira.']);
ev('cerebros_b1', '¡CEREBROS!', 'b', 3, 0, 0, 0, ALL, 0, ['Turno especial: +1 de Infección. Todas las rutas se activan (tú eliges el orden) y cada unidad Zed que gane un combate avanza otra vez de inmediato (repite si es necesario). Después, termina el turno: no hay fase de Acciones.'], { sp: 1, cer: 1, order: 1, skulls: 1 });
ev('cerebros_b2', '¡CEREBROS!', 'b', 4, 0, 0, 0, ALL, 0, ['Turno especial: +2 de Infección. Todas las rutas se activan y cada Zed que gane un combate avanza otra vez. No hay fase de Acciones.'], { sp: 1, cer: 1, order: 1, skulls: 2 });
ev('fin_b1', 'De una vez por todas, buenas noches', 'b', 5, 1, 'B', 'd', ['F','M','A','A'], 0, ['Al inicio de esta fase: ¡habéis ganado!', '«La melancolía te invade al despertar del estado de salvaje supervivencia…»'], { fin: 1 });
ev('fin_b2', 'Para bien o para mal, yo soy el que tiene el arma', 'b', 5, 2, 'B', 1, ['D2'], 0, ['Al inicio de la fase de los Zeds: roba Destino para saber qué ruta se activa 2 veces. Al inicio de la fase de Acciones, si seguís vivos: ¡habéis ganado!'], { fin: 1 });

/* ---- VERDES (Nivel II) ---- */
ev('errantes', 'Zeds errantes', 'g', 1, 1, 'B', 0, ['A','F','B'], 1, ['Al inicio, roba Destino: elige una unidad de Civiles o Héroe en la Ruta Destinada (no en el Centro ni en un espacio Inicial): sufre de inmediato un ataque Cuerpo a Cuerpo en la columna «Igual» (aplica Terreno). Solo sufre Impactos, no se retira.']);
ev('despensa', 'Encuentras una despensa', 'g', 1, 0, 0, 'd', ['A','M'], 2, ['Al final de esta fase: si una unidad de jugador está en el Distrito Comercial, obtienes 4 Suministros. (¡Botín!)']);
ev('agua', 'El suministro de agua se ha contaminado', 'g', 1, 1, 'B', 'd', ['M','B'], 2, ['Al inicio: tira 1 dado para determinar tus pérdidas. Pierdes esa cantidad en cualquier combinación de: a) Suministros, b) Impactos a unidades de jugador.']);
ev('cerebros_g', '¡CEREBROS!', 'g', 2, 0, 0, 0, ALL, 0, ['Turno especial: +3 de Infección. Todas las rutas se activan y cada Zed que gane un combate avanza otra vez. No hay fase de Acciones.'], { sp: 1, cer: 1, order: 1, skulls: 3 });
ev('heroe_g', 'Llega un Héroe', 'g', 2, 2, 'B', 'd', ['B','F','A'], 2, ['Al inicio: coge un nuevo Héroe disponible al azar y colócalo en el Centro de la Ciudad o en cualquier espacio Inicial.'], { id2: 'heroe_b' });
ev('marines', 'El equipo de Marines despliega sus tropas', 'g', 2, 1, 'B', 1, ['M','A'], 2, ['Al inicio, roba Destino: 1. Coloca la unidad de Marines en el espacio Inicial de la Ruta Destinada. 2. +4 de Munición.', 'Los Marines mueven 1 espacio cada fase 4R y hasta 3 por Acción de Mover. 1 columna a favor al combatir; disparos de Largo Alcance con 1 en contra.']);
ev('caos_abs', 'Caos absoluto', 'g', 2, 1, 'B', 1, ['B','F','M'], 3, ['Cada espacio con nombre que pase a estar controlado por Zeds este turno recibe 2 fichas de Caos (en lugar de 1). Solo puedes retirar 1 ficha por turno en la fase de Mantenimiento.'], { chaos2: 1 });
ev('toxicos', 'Zeds Tóxicos', 'g', 2, 1, 'B', 1, ['A','A'], 2, ['Al inicio: 1. Coloca un nuevo Zed en el Inicial de la Autovía. 2. Pon la ficha de Tóxicos en el Zed Normal más fuerte: sus combates (y los de su Horda) suben la Infección +3 en vez de +1 hasta que sea eliminado.']);
ev('rapidos', 'Zeds Rápidos', 'g', 3, 1, 'B', 'd', ['B','B'], 2, ['Al inicio: 1. Coloca un nuevo Zed en el Inicial del Bosque. 2. Pon la ficha de Rápidos en el Zed Normal más fuerte: se mueve dos veces cada vez que se activa (luchando tras cada movimiento).']);
ev('turba', 'Aparece una turba no identificada', 'g', 3, 2, 'B', 0, ['M','A'], 3, ['Al inicio, roba Destino: 1. Si la Infección es 8 o mayor, coloca una nueva unidad de Súper Zeds en el Inicial de la ruta. 2. Si es 7 o menor, coloca en su lugar a los Supervivientes V.I.P. (Refugiados especiales).']);
ev('saqueadores', '¡Aparecen Saqueadores!', 'g', 3, 1, 'B', 'd', ['F','B'], 1, ['Al inicio: coloca la unidad de Saqueadores en el Inicial de la ruta de superficie con más Caos (a tu elección si hay empate). Se mueve 1 espacio por turno hacia el Centro, incluyendo este turno. Si llega, pierdes Suministros y Munición igual a su Fuerza.']);
ev('helicoptero', 'Ataque del helicóptero de la Guardia Nacional', 'g', 3, 1, 'B', 0, ['F','A'], 3, ['Al inicio: elige una unidad u Horda Zed en un espacio no Inicial de la superficie y tira 2 dados: 2-5 → 1 Impacto; 6-9 → 2 Impactos; 10-12 → 3 Impactos. Aplícalos a la unidad u Horda elegida.']);
ev('duros', '¡Zeds duros de mollera!', 'g', 4, 1, 'B', 'd', ['M','F'], 1, ['Durante esta fase las unidades defensoras no reciben Modificadores por Terreno. Los Zeds destruyen de inmediato cualquier Barricada en un espacio al que entren, antes de resolver el combate.'], { noTerrain: 1, smash: 1 });
ev('eficiencia', 'Eficiencia en el Hospital', 'g', 4, 2, 'B', 'd', ['F','M','A'], 2, ['Durante esta fase, elige una opción: a) 2 Acciones de Curar gratis en el Hospital (sin reducir la Infección); b) −2 de Infección; c) −1 de Infección y 1 Acción de Curar gratis en el Hospital (sin reducir la Infección).']);
ev('oh_malo', 'Oh, esto es malo…', 'g', 4, 0, 0, 'd', ALL, 3, ['Al inicio: 1. Roba Destino y coloca una unidad Zed en el espacio n.º 1 de la Ruta Destinada (límite de agrupamiento). 2. Retira todas las fichas de Impacto de los Zeds.', 'Después se activan todas las rutas (tú eliges el orden).'], { sp: 1, order: 1 });
ev('que_demonios', '¿Qué demonios es eso?', 'g', 4, 1, 0, 'd', ALL, 2, ['Al inicio: 1. Aumenta la Infección de inmediato hasta 13 y resuelve un Brote Descontrolado. 2. Retira todas las fichas de Impacto de los Zeds.', 'Después se activan todas las rutas (tú eliges el orden).'], { sp: 1, order: 1 });
ev('donde_todos', '¿De dónde salen todos?', 'g', 3, 1, 0, 'd', ALL, 1, ['Al inicio: 1. Coloca una nueva unidad Zed en cada espacio de Pueblo controlado por Zeds (límite de agrupamiento). 2. Retira todas las fichas de Impacto de los Zeds.', 'Después se activan todas las rutas.'], { sp: 1, order: 1 });
ev('guardia', '¡Llega la Guardia Nacional!', 'g', 3, 0, 0, 0, [], 0, ['Roba una carta de Destino inmediatamente y coloca la unidad de la Guardia Nacional en el Inicial de la Ruta Destinada. Si indica el Túnel, pasa a ser a elección de los jugadores.', 'La Guardia mueve 1 espacio cada fase 4R y 1 por Acción de Mover. Necesita 2 de Munición por ataque. Tras colocarla, se acaba este turno (roba la siguiente carta).'], { sp: 1, guardia: 1 });
ev('fin_g', '¿Quieres un trozo de mí?', 'g', 5, 1, 'B', 'd', ['M','M','B','F'], 0, ['¡Habéis ganado!', 'Durante un instante lamentáis vuestras pérdidas…'], { fin: 1 });

/* ---- AMARILLAS (Nivel III) ---- */
ev('noelle', 'Noelle «Hell» Razer', 'y', 1, 2, 'B', 'd', ['A','B'], 1, ['Al inicio, roba Destino y coloca la unidad con peana de Noelle (Propagadora de Enfermedad) en el Inicial de la Ruta Destinada. Mientras esté en juego fuera de un espacio Inicial: +1 de Infección al inicio de cada fase de Infección.']);
ev('granero', 'Encuentras un granero lleno', 'y', 1, 1, 'B', 'd', ['M','B'], 3, ['Al final de esta fase: si una unidad de jugador está en la Granja, aumenta tus Suministros en 1 dado. (¡Botín!)']);
ev('tsunami', 'Tsunami zombi', 'y', 2, 1, 'B', 1, ALL, 3, ['Al inicio: coloca una nueva unidad Zed en el espacio Inicial de cada ruta (límite de agrupamiento).'], { order: 1 });
ev('descubrimiento', 'Descubrimiento en la Investigación', 'y', 2, 1, 'B', 1, ['A'], 2, ['Al final de esta fase: si una unidad de jugador está en la Universidad, revela sin coste la siguiente carta de Investigación. (¡Botín!)']);
ev('jornada', 'Trabajando una jornada doble', 'y', 2, 1, 'B', 1, ['M','A'], 3, ['Durante esta fase puedes aumentar la Infección (hasta 3 veces). Cada vez que lo hagas puedes: a) obtener una Acción de Curar gratis o bien b) realizar una Acción de Investigar gratis.']);
ev('catastrofe', 'Catástrofe nuclear', 'y', 2, 1, 'B', 'd', ['A','B','F'], 3, ['Al inicio: comprueba el espacio de la Central Nuclear: 1. Cualquier unidad allí sufre 2 Impactos y se retira. 2. Coloca una ficha de Caos en ese espacio. 3. Ninguna unidad puede entrar allí este turno («No Pasar»).']);
ev('flambeados', 'Zeds flambeados', 'y', 2, 1, 0, 0, ['M','F'], 2, ['Durante esta fase, cada unidad u Horda Zed que entre o salga de un espacio con Caos obtiene 2 columnas en contra en sus ataques Cuerpo a Cuerpo. Cada unidad Zed que entre o salga de un espacio con Caos sufre 1 Impacto tras mover (después de resolver el combate).'], { flamed: 1 });
ev('super_enloq', 'Los Súper Zeds enloquecen', 'y', 3, 0, 'B', 2, ALL, 4, ['Al final de esta fase: activa todos los Súper Zeds (únicamente), empezando por los más cercanos al Centro. Reciben 2 columnas en contra al atacar durante esta activación.']);
ev('desesperacion', 'Aumenta la desesperación', 'y', 3, 2, 'B', 2, ['A','F','B'], 2, ['Al inicio: 1. Suma el número de unidades Zed (incluyendo Súper Zeds y Propagadores) en los espacios n.º 2, n.º 1 y n.º 0. 2. Pierdes esa cantidad en cualquier combinación de Suministros, Munición y/o Impactos a unidades de jugador.']);
ev('moteros', 'Banda de moteros Los Ángeles de Petra', 'y', 3, 2, 'B', 'd', ['A','A'], 3, ['Al inicio: 1. Coloca la unidad (Civiles Especiales) Ángeles de Petra en el Centro de la Ciudad. 2. −1 Suministro; no hay penalización si no puedes perder esa cantidad.']);
ev('inteligentes', 'Zeds Inteligentes', 'y', 3, 1, 'B', 'd', ['F','F'], 3, ['Al final de esta fase: 1. Coloca un nuevo Zed en el Inicial de las Afueras. 2. Pon la ficha de Inteligentes en el Zed Normal más fuerte: obtiene 1 columna en contra cuando ataca hasta que sea eliminado.']);
ev('monstruo', '¿Quién es el verdadero monstruo, Doc?', 'y', 3, 0, 'B', 'd', ['F','A'], 0, ['Durante esta fase puedes «dar de alta» del Hospital hasta 2 unidades (solamente) y mandarlas al Cementerio: revela sin coste la siguiente carta de Investigación por cada unidad «dada de alta» de esta forma.']);
ev('soldados', 'Soldados de fortuna', 'y', 3, 1, 'B', 0, ['M','B'], 4, ['Durante esta fase, todos tus ataques con Arma de Fuego obtienen 1 columna a favor y no gastan Munición. Al final de esta fase, tira 1 dado para determinar cuánto se paga a estos mercenarios: pierdes esa cantidad en cualquier combinación de Suministros o Impactos a unidades de jugador.'], { mercs: 1 });
ev('que_diablos', '¿Qué diablos? ¿Hay más?', 'y', 3, 2, 0, 'd', ALL, 2, ['Al inicio: 1. Cada unidad Zed en un espacio con nombre se recupera a su cara de Fuerza completa. 2. Retira todas las fichas de Impacto de los Zeds.', 'Después se activan todas las rutas.'], { sp: 1, order: 1 });
ev('cerebros_y1', '¡CEREBROS!', 'y', 3, 0, 0, 0, ALL, 0, ['Turno especial: +2 de Infección. Todas las rutas se activan; cada Zed que gane un combate avanza otra vez. No hay fase de Acciones.'], { sp: 1, cer: 1, order: 1, skulls: 2 });
ev('crisis', 'Crisis nerviosa', 'y', 4, 1, 'B', 'd', ['M','A'], 1, ['Al inicio: elige una unidad de Héroe en o adyacente al Centro de la Ciudad (pero no en una Cama de Hospital) y tira 1 dado: 1 = Suicida (sufre 2 Impactos); 2-5 = Autodestructivo (sufre 1 Impacto); 6 = «¡Estoy bien!» (sin efecto).']);
ev('campanas', 'Campanas en la cafetería del infierno', 'y', 4, 2, 'B', 0, ['M','B'], 2, ['Al inicio: retira 1 Impacto, si es posible, a cada unidad Zed y Súper Zed en o adyacente a un espacio de Ciudad o de Pueblo sin unidades de jugador en él.']);
ev('cerebros_y2', '¡CEREBROS!', 'y', 2, 0, 0, 0, ALL, 0, ['Turno especial: +4 de Infección. Todas las rutas se activan; cada Zed que gane un combate avanza otra vez. No hay fase de Acciones.'], { sp: 1, cer: 1, order: 1, skulls: 4 });
ev('fin_y', 'Es hora de actuar o callar', 'y', 5, 1, 'B', 1, ALL, 0, ['¡Habéis ganado!', 'A tu alrededor todo es caos mientras los Zeds retroceden…'], { fin: 1 });

/* ---- NARANJAS (Nivel IV) ---- */
ev('frenesi', 'Frenesí Súper Zed', 'o', 4, 2, 'B', 'd', ALL, 2, ['Al final de esta fase: activa todos los Súper Zeds (solamente), empezando por los más cercanos al Centro. Obtienen 2 columnas en contra al atacar durante esta activación.']);
ev('materiales', 'Materiales de Investigación', 'o', 3, 1, 'B', 0, ['B','T','M'], 2, ['Al final de esta fase: si una unidad de jugador está en el espacio de la Central Nuclear, revela sin coste la siguiente carta de Investigación. (¡Botín!)']);
ev('misiles', 'Misiles del dron del Ejército', 'o', 4, 2, 'B', 1, ['B','T','T'], 1, ['Al inicio: elige un espacio ocupado por Zeds en la superficie y tira 1 dado: 1-2 → 1 Impacto a una unidad Zed allí; 3-4 → 2 Impactos en total; 5-6 → 3 Impactos en total.']);
ev('bomberos', 'Los Aldeanos organizan unidades de bomberos', 'o', 3, 2, 'B', 2, ['T','T','M'], 3, ['Al final de esta fase: puedes retirar cualquier cantidad de fichas de Caos en espacios de Pueblo; +1 de Infección por cada una que retires.']);
ev('contaminacion', 'Contaminación en el Hospital', 'o', 4, 1, 'B', 'd', ['F','F','T','T'], 3, ['Al inicio: 1. +1 de Infección por cada unidad en una Cama de Hospital y en las Oficinas del Personal. 2. Retira la ficha de Elwood Berra si está en juego.']);
ev('renqueantes', 'Zeds renqueantes', 'o', 3, 2, 'B', 0, ['B','A','A','T'], 2, ['Al inicio, roba Destino: elige una unidad de Civiles o Héroe en la Ruta Destinada (no en el Centro ni en un espacio Inicial): sufre un ataque Cuerpo a Cuerpo en la columna «Igual» (aplica Terreno). Solo sufre Impactos, no se retira.']);
ev('accidente', 'Accidente en el Laboratorio', 'o', 2, 1, 'B', 'd', ['A','T','T'], 2, ['Al inicio, tira 1 dado: 1-5 → añade una carta de Investigación Inicial al azar a la parte superior del mazo de Investigación; 6 → sin efecto.']);
ev('elwood', 'Elwood Berra llega al Hospital', 'o', 3, 2, 'B', 0, ['B','T'], 2, ['Al inicio: coloca la ficha de Elwood Berra sobre el marcador de Infección. Proporciona −1 de Infección al final de cada fase de Mantenimiento.']);
ev('rumores', 'Rumores de contagio por el aire', 'o', 2, 1, 0, 2, ALL, 1, ['No pueden realizarse Acciones de Mover en la superficie durante esta fase (el viento transmite la enfermedad y paraliza cualquier movimiento).'], { noSurfaceMove: 1 });
ev('hace_falta', 'Hace falta un Pueblo…', 'o', 2, 2, 'B', 1, ['T','M'], 2, ['Al inicio: 1. Sustituye una unidad de Aldeanos, Refugiados o Civiles en cualquier ruta por una nueva unidad Zed Normal. 2. Coloca la unidad reemplazada en el Hospital por su cara de Fuerza reducida con una ficha de ECG.']);
ev('no_comer', 'No den de comer a los Zeds', 'o', 3, 1, 'B', 'd', ['T','T','A'], 2, ['Al inicio: 1. Retira 1 Impacto, si es posible, a cada unidad Zed Normal en o adyacente a un espacio de Pueblo o Ciudad que no tenga unidades de jugador en él.']);
ev('misterioso', 'El misterioso Dr. Marteuse', 'o', 3, 0, 0, 0, ['T','A','F'], 4, ['Al inicio: 1. Tienes que descartar una carta de Destino de «Guardar para más tarde» (sin jugarla), si tienes alguna. 2. Aumenta la Infección en 1 dado. 3. Coloca una nueva unidad Zed en el espacio Inicial de cada ruta (límite de agrupamiento).']);
ev('alcantarilla', 'Zeds de alcantarilla', 'o', 2, 0, 'B', 1, ['T','T'], 1, ['¡Los Zeds emergen desde el Túnel! Al final de esta fase, todas las unidades Zed en los siguientes espacios del Túnel intentan moverse hacia la superficie (haz una tirada de Cripta primero): n.º 7 → espacio de la Universidad; n.º 6 → Central Nuclear; n.º 4 → Mina; n.º 3 y n.º 5 → Granja. Si no hay espacio, se quedan donde están.'], { sewer: 1 });
ev('civ_heroicos', 'Llegan Civiles Heroicos', 'o', 1, 1, 'B', 'd', ['T','A'], 2, ['Al inicio: coge al azar una nueva unidad de Civiles Heroicos y colócala en el Centro de la Ciudad.']);
ev('murcielagos', 'Enjambre de murciélagos del Túnel', 'o', 1, 0, 'B', 'd', ['B','T','T'], 3, ['Al inicio, Después, busca la unidad de jugador que esté en la ruta del Túnel y más alejada del Centro de la Ciudad. ¡Ha molestado a una colonia de murciélagos infectados! Resuelve de inmediato: 1. +1 de Infección. 2. Esa unidad sufre 1 Impacto y se retira.']);
ev('fin_o', '¡Fin de la partida, tío!', 'o', 5, 0, 'B', 2, ALL, 0, ['¡Habéis ganado!', 'Es difícil diferenciar a los malheridos supervivientes de los Zeds que antes atacaban…'], { fin: 1 });

/* ---- ROJAS (Nivel V) ---- */
ev('brote_local', 'Brote local de Zeds', 'r', 1, 1, 'B', 1, ['F','M','T'], 2, ['Al inicio, Z. Durante este turno, por cada unidad de Civiles Normales eliminada o ingresada en el Hospital (tras su tirada de Salvación), coloca una nueva unidad Zed en el espacio en el que fue eliminada y aplica el límite de agrupamiento si es necesario. Los nuevos Zeds no se mueven este turno.'], { outbreakLocal: 1 });
ev('experimentos', 'Experimentos explosivos', 'r', 2, 2, 'B', 'd', ['B','B','F','F'], 2, ['Al inicio, tira 1 dado: 1-5 → añade una carta de Investigación Inicial al azar a la parte superior del mazo de Investigación; 6 → sin efecto. Aumenta la Infección en 1 dado.']);
ev('artefacto', 'Encuentras un artefacto alienígena', 'r', 2, 2, 'B', 'd', ['A','A','T'], 3, ['Al inicio, roba Destino: 1. Coloca una nueva unidad de Súper Zeds en el espacio número (1 dado) de la Ruta Destinada. 2. Revela sin coste la siguiente carta del mazo de Investigación.']);
ev('feria', 'La feria de las tinieblas', 'r', 2, 0, 'B', 'd', ALL, 3, ['Después de moverse los Zeds, en cada espacio de Cripta tira 1 dado: 1 = coloca 2 nuevas unidades Zed en ese espacio; 2-5 = coloca 1 nueva unidad Zed; 6 = sin efecto.']);
ev('oh_no', '¡Oh, no! ¡Otra vez no!', 'r', 3, 1, 'B', 'd', ['F','A','B'], 2, ['Al inicio: revisa las fichas de Mejora Zed (Inteligentes, Rápidos, etc.) que se hayan usado y retirado de la partida, si las hay. Elige una de ellas y colócala en la unidad Zed Normal más fuerte (a tu elección si hay empate).']);
ev('doc_problema', 'Doc… Tenemos un gran problema', 'r', 3, 1, 'B', 'd', ['B','F','T'], 3, ['Al inicio: 1. +1 de Infección por cada unidad en una Cama de Hospital y en las Oficinas del Personal. 2. Retira la ficha de Elwood Berra si está en juego (¡le echan la culpa al ayudante!).']);
ev('irrupcion', 'Una irrupción desde las profundidades', 'r', 3, 1, 'B', 'd', ['T','T'], 3, ['¡Los Zeds emergen tropezando desde el Túnel hacia Farmingdale! Al final de esta fase, todas las unidades Zed en los espacios del Túnel n.º 7, 6, 4, 3 y 5 intentan moverse a la superficie (Universidad, Central Nuclear, Mina, Granja; tirada de Cripta primero). Si no hay sitio, se quedan.'], { sewer: 1 });
ev('no_detendran', '¡No se detendrán ante nada!', 'r', 3, 2, 'B', 'd', ['M','M','T','T'], 2, ['Durante esta fase las unidades defensoras no reciben Modificadores por Terreno. Los Zeds destruyen de inmediato cualquier Barricada en un espacio al que entren, antes de resolver cualquier combate Cuerpo a Cuerpo en ese espacio.'], { noTerrain: 1, smash: 1 });
ev('desde_lab', 'Desde el laboratorio del Dr. Marteuse', 'r', 3, 1, 'B', 'd', ['F','B','T'], 2, ['Al inicio: a) Si no hay unidades de Súper Zeds en juego, coloca una nueva unidad de Súper Zeds en la Oficina del Dr. Marteuse. b) Si ya hay alguna unidad de Súper Zeds en juego, coloca una unidad Zed Normal allí en su lugar.']);
ev('hinchados', 'Los Zeds hinchados estallan', 'r', 3, 1, 'B', 'd', ['F','A','M'], 2, ['Al inicio, roba Destino: 1. Elimina la unidad Zed (incluyendo Súper Zeds o Propagadores) más cercana al Centro en la Ruta Destinada. 2. Realiza un ataque independiente con Arma de Fuego de Fuerza 4 contra cada unidad adyacente de jugador o Zed. 3. Todas las unidades, incluyendo Refugiados, son afectadas por este ataque. Las unidades en espacios Iniciales no se ven afectadas.']);
ev('atajos', '«Atajos» experimentales', 'r', 3, 1, 'B', 1, ['M','A','T'], 3, ['Al inicio de esta fase, durante la cual puedes infligir 1 Impacto a un Héroe en el Laboratorio y tirar 1 dado: 1 = sin efecto; 2-6 = revela sin coste la siguiente carta del mazo de Investigación. Puedes hacer esto tantas veces como quieras.']);
ev('no_escapatoria', 'No hay escapatoria', 'r', 3, 0, 'B', 'd', ['A','F','T','T'], 2, ['Durante esta fase, tras el primer ataque Zed, ningún bando se retira: en su lugar, la unidad u Horda Zed ataca de inmediato otra vez (si puede). No puedes usar habilidades para evitar el segundo ataque.'], { noRetreatOnce: 1 });
ev('conductos', 'Conexión por los conductos del vapor', 'r', 3, 1, 'B', 0, ['A','A','B','B'], 3, ['Al inicio de esta fase. Por cada unidad Zed en un espacio de Cripta, tira 1 dado: 1-2 = intenta entrar en la Central Nuclear; 3-5 = intenta entrar en la Granja (primero tira en la tabla de Cripta); 6 = no pasa nada. Si no hay sitio, se queda donde está.'], { vents: 1 });
ev('caos_control', 'El caos se extiende sin control', 'r', 3, 1, 0, 0, ['M','T','A'], 2, ['Cada espacio con nombre que pase a estar controlado por Zeds este turno recibe 2 fichas de Caos (en lugar de 1). Solo puedes retirar 1 ficha por turno, como es habitual, durante la fase de Mantenimiento (ver sección 7.2).'], { chaos2: 1 });
ev('fin_r', 'Por fin ha terminado la larga pesadilla', 'r', 5, 0, 'B', 2, ['*','*'], 0, ['¡Habéis ganado!', 'Ninguno de los supervivientes volverá a ser el mismo…'], { fin: 1 });
/* El Dr. Marteuse («¡Aquí está el Doctor!») y las cartas del Jugador Zed se usan solo en el modo Versus (no incluido). */

/* orden estable de nombres de archivo de imagen = id */
